<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\webhook.sample.application\webhook.sample.application.csproj"/>
        <ProjectReference Include="..\webhook.sample.repository\webhook.sample.repository.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="data\"/>
        <Folder Include="Services\"/>
    </ItemGroup>

</Project>
