<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="JsonSchema.Net" Version="9.4.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\webhook.sample.domain\webhook.sample.domain.csproj"/>
    </ItemGroup>

</Project>
