<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\webhook.sample.infrastructure\webhook.sample.infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.12"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.13"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.13"/>
    </ItemGroup>

</Project>
